= Configuring Plugins in Red Hat OpenShift DevSpaces
:navtitle: Home

== Introduction

Welcome to this quick course on _Configuring Plugins in Red Hat OpenShift DevSpaces_.
This course is the `fifth` in a series of `five` courses about Red Hat OpenShift DevSpaces:

. https://redhatquickcourses.github.io/devspaces-intro[Introduction to Red Hat OpenShift Dev Spaces^]
. https://redhatquickcourses.github.io/devspaces-admin[Red Hat OpenShift Dev Spaces Administration^] 
. https://redhatquickcourses.github.io/devspaces-security[Securing Access to Red Hat OpenShift Dev Spaces^]
. https://redhatquickcourses.github.io/devspaces-workspaces[Creating and Customizing Workspaces in Red Hat OpenShift Dev Spaces^]
. Configuring Plugins in Red Hat OpenShift Dev Spaces (_This course_)

This course covers how to configure plugin registries, and install plugins in Dev Spaces.

NOTE: The hands-on labs for this course have been tested on *Red Hat OpenShift Dev Spaces 3.16*. The labs should mostly work on minor update releases of Dev Spaces. If you encounter any issues, please open a GitHub issue in the course repository.

== Course Objectives

The overall objectives of this course include:

* Describe the concept of a plugin registry, and configure Dev Spaces to use different types of plugin registries
* Enable IDE plugins automatically at workspace start up
* Configure and deploy a custom instance of the embedded Open VSX plugin registry with a set of custom plugins for the IDE

== Course Prerequisites

* You must complete the first four courses in the learning path covering the basics of Dev Spaces, its administration, security, and creating/managing workspaces
* Basic knowledge of OpenShift (or Kubernetes) administration
* Knowledge of building Docker or Podman containers
* Deploying container images on OpenShift or Kubernetes
* OpenShift or Kubernetes User and Role Administration

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Ravi Srinivasan
* Rutuja Deshmukh
* Anna Swicegood
* Caitlyn Rymarchyk
* Anton Giertli
* Anatolii Bazko

== Classroom Environment

You must continue to use the classroom you provisioned for Dev Spaces in the second course (__Red Hat OpenShift Dev Spaces Administration__) of the learning path. You must have a valid installation of Dev Spaces using any of the approaches taught in the second course.
